[build]
builder = "nixpacks"
buildCommand = "npm run build && npm run db:seed"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/auth/me"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
internalPort = 3000
